version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "8081:80"
  web:
    build: ./web
    working_dir: /app
    volumes:
      - type: bind
        source: ./web/src
        target: /var/www/html/
    ports:
      - "8080:80"
